import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import SideBar from "./components/sidebar";
import Link from "next/link";
import Navigation from "./components/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        < NavBar />
        <div className="min-h-screen w-full bg-[#191414] text-white p-6">
            <div className="flex gap-6 mt-20">
              <SideBar />
              <div className="flex-1">
                < Navigation />
                {children}
              </div>
            </div>
        </div>
      </body>
    </html>
  );
}
